name: Deploy Laravel Sail App

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  pull-code:
    name: Pull Latest Code
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Server & Pull Code
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/filip/estore-admin Change this to your actual path
            git pull origin main  # Pull latest code

  run-containers:
    name: Start Sail Containers
    runs-on: ubuntu-latest
    needs: pull-code  # This job runs only after 'pull-code' completes successfully
    steps:
      - name: Connect to Server & Start Containers
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/filip/estore-admin  # Change this to your actual path
            ./vendor/bin/sail up --build -d  # Start/rebuild the new containers

  run-migrations:
    name: Run Migrations
    runs-on: ubuntu-latest
    needs: run-containers  # This job runs only after 'run-containers' completes successfully
    steps:
      - name: Connect to Server & Run Migrations
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/filip/estore-admin  # Change this to your actual path
            ./vendor/bin/sail npm run build
            ./vendor/bin/sail artisan migrate  # Run migrations

