name: Deploy Laravel Sail App

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  pull-code:
    name: Pull Latest Code
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Server & Pull Code
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/estore-backend
            git pull origin main
            composer install
            npm install

  run-containers:
    name: Start Sail Containers
    runs-on: ubuntu-latest
    needs: pull-code  # This job runs only after 'pull-code' completes successfully
    steps:
      - name: Connect to Server & Start Containers
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/estore-backend
            ./vendor/bin/sail up --build -d

  run-migrations:
    name: Run Migrations
    runs-on: ubuntu-latest
    needs: run-containers  # This job runs only after 'run-containers' completes successfully
    steps:
      - name: Connect to Server & Run Migrations
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/estore-backend
            ./vendor/bin/sail artisan down
            ./vendor/bin/sail npm build
            ./vendor/bin/sail artisan migrate
            ./vendor/bin/sail artisan up

